### PR TITLE
#25 Containerize the project with Docker

### PR DESCRIPTION
**Pull request by bhatvineeth**

### CODE REVIEW

**Review by sjathin — CHANGES_REQUESTED** [review]
IMO it would be better to add the steps to run the application in the readme file.

**Comment by bhatvineeth** [comment]
> IMO it would be better to add the steps to run the application in the readme file.

Agree. Will update that as well

**Comment by bhatvineeth** [comment]
@sjathin updated readme

**Comment by sjathin** [comment]
Just an FYI, while merging this will be merged to master.

**Review by sjathin — APPROVED** [review]

**Comment by bhatvineeth** [comment]
> Just an FYI, while merging this will be merged to master.

Yes, as the develop branch is outdated since we merged this [license update](https://github.com/bhatvineeth/SchedulingSimulation/pull/21) PR to master. 
We agreed to update the master and create a new develop once everything is set.

**Pull request merged**
